name: Build and Push Image
on: [push]
jobs:
  Build-And-Push-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: toliyansky/ansible-deployer:1.0.1 toliyansky/ansible-deployer:latest